apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
  - protocol: TCP
    port: 80        # service port
    targetPort: 80  # container port
  type: NodePort    # exposes service on a port of kind node

